/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello */

#ifndef _Included_Hello
#define _Included_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hello
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hello_init
  (JNIEnv *, jobject);

/*
 * Class:     Hello
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hello_exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
